In [29]:
import pandas as pd
import numpy as np

In [3]:
#raw data
df = pd.read_csv("HomeC.csv")
df

/tmp/ipykernel_61/3623732865.py:1: DtypeWarning: Columns (0,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("HomeC.csv")

,time,use [kW],gen [kW],House overall [kW],Dishwasher [kW],Furnace 1 [kW],Furnace 2 [kW],Home office [kW],Fridge [kW],Wine cellar [kW],...,visibility,summary,apparentTemperature,pressure,windSpeed,cloudCover,windBearing,precipIntensity,dewPoint,precipProbability
0,1451624400,0.932833,0.003483,0.932833,0.000033,0.020700,0.061917,0.442633,0.124150,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
1,1451624401,0.934333,0.003467,0.934333,0.000000,0.020717,0.063817,0.444067,0.124000,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
2,1451624402,0.931817,0.003467,0.931817,0.000017,0.020700,0.062317,0.446067,0.123533,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
3,1451624403,1.022050,0.003483,1.022050,0.000017,0.106900,0.068517,0.446583,0.123133,0.006983,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
4,1451624404,1.139400,0.003467,1.139400,0.000133,0.236933,0.063983,0.446533,0.122850,0.006850,...,10.00,Clear,29.26,1016.91,9.18,cloudCover,282.0,0.0000,24.40,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503906,1452128306,1.599333,0.003233,1.599333,0.000050,0.104017,0.625033,0.041750,0.005233,0.008433,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503907,1452128307,1.924267,0.003217,1.924267,0.000033,0.422383,0.637733,0.042033,0.004983,0.008467,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503908,1452128308,1.978200,0.003217,1.978200,0.000050,0.495667,0.620367,0.042100,0.005333,0.008233,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503909,1452128309,1.990950,0.003233,1.990950,0.000050,0.494700,0.634133,0.042100,0.004917,0.008133,...,8.74,Light Rain,29.45,1011.49,6.72,0.31,186.0,0.0101,31.27,0.51
503910,\,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#전처리 데이터
df = pd.read_csv("HomeC2.csv")
df

,time,House overall,Dishwasher,Home office,Fridge,Wine cellar,Garage door,Barn,Well,Microwave,...,cloudCover,windBearing,precipIntensity,dewPoint,precipProbability,month,day,weekday,hour,minute
0,2016-01-01 14:00:00,0.932833,0.000033,0.442633,0.124150,0.006983,0.013083,0.031350,0.001017,0.004067,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,0
1,2016-01-01 14:01:00,0.934333,0.000000,0.444067,0.124000,0.006983,0.013117,0.031500,0.001017,0.004067,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,1
2,2016-01-01 14:02:00,0.931817,0.000017,0.446067,0.123533,0.006983,0.013083,0.031517,0.001000,0.004067,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,2
3,2016-01-01 14:03:00,1.022050,0.000017,0.446583,0.123133,0.006983,0.013000,0.031500,0.001017,0.004067,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,3
4,2016-01-01 14:04:00,1.139400,0.000133,0.446533,0.122850,0.006850,0.012783,0.031500,0.001017,0.004067,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503905,2016-12-16 12:25:00,1.601233,0.000050,0.041783,0.005267,0.008667,0.013483,0.032283,0.000983,0.003800,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,25
503906,2016-12-16 12:26:00,1.599333,0.000050,0.041750,0.005233,0.008433,0.013433,0.032200,0.000950,0.003800,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,26
503907,2016-12-16 12:27:00,1.924267,0.000033,0.042033,0.004983,0.008467,0.012933,0.032283,0.001000,0.003750,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,27
503908,2016-12-16 12:28:00,1.978200,0.000050,0.042100,0.005333,0.008233,0.012817,0.032183,0.000950,0.003767,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,28
503909,2016-12-16 12:29:00,1.990950,0.000050,0.042100,0.004917,0.008133,0.012833,0.032167,0.000950,0.003767,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,29

In [5]:
df['time'] = pd.to_datetime(df['time'])
df = df.set_index('time')

In [6]:
df

,House overall,Dishwasher,Home office,Fridge,Wine cellar,Garage door,Barn,Well,Microwave,Living room,...,cloudCover,windBearing,precipIntensity,dewPoint,precipProbability,month,day,weekday,hour,minute
time,,,,,,,,,,,,,,,,,,,,,
2016-01-01 14:00:00,0.932833,0.000033,0.442633,0.124150,0.006983,0.013083,0.031350,0.001017,0.004067,0.001517,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,0
2016-01-01 14:01:00,0.934333,0.000000,0.444067,0.124000,0.006983,0.013117,0.031500,0.001017,0.004067,0.001650,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,1
2016-01-01 14:02:00,0.931817,0.000017,0.446067,0.123533,0.006983,0.013083,0.031517,0.001000,0.004067,0.001650,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,2
2016-01-01 14:03:00,1.022050,0.000017,0.446583,0.123133,0.006983,0.013000,0.031500,0.001017,0.004067,0.001617,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,3
2016-01-01 14:04:00,1.139400,0.000133,0.446533,0.122850,0.006850,0.012783,0.031500,0.001017,0.004067,0.001583,...,0.75,282.0,0.0000,24.40,0.00,1,1,Friday,14,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-16 12:25:00,1.601233,0.000050,0.041783,0.005267,0.008667,0.013483,0.032283,0.000983,0.003800,0.000967,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,25
2016-12-16 12:26:00,1.599333,0.000050,0.041750,0.005233,0.008433,0.013433,0.032200,0.000950,0.003800,0.000933,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,26
2016-12-16 12:27:00,1.924267,0.000033,0.042033,0.004983,0.008467,0.012933,0.032283,0.001000,0.003750,0.001000,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,27
2016-12-16 12:28:00,1.978200,0.000050,0.042100,0.005333,0.008233,0.012817,0.032183,0.000950,0.003767,0.000950,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,28
2016-12-16 12:29:00,1.990950,0.000050,0.042100,0.004917,0.008133,0.012833,0.032167,0.000950,0.003767,0.000950,...,0.31,186.0,0.0101,31.27,0.51,12,16,Friday,12,29

In [10]:
#11월 까지의 데이터
df0 = df[:'2016-11-30 23:59']
df0

,House overall,Dishwasher,Home office,Fridge,Wine cellar,Garage door,Barn,Well,Microwave,Living room,...,cloudCover,windBearing,precipIntensity,dewPoint,precipProbability,month,day,weekday,hour,minute
time,,,,,,,,,,,,,,,,,,,,,
2016-01-01 14:00:00,0.932833,0.000033,0.442633,0.124150,0.006983,0.013083,0.031350,0.001017,0.004067,0.001517,...,0.75,282.0,0.0,24.40,0.0,1,1,Friday,14,0
2016-01-01 14:01:00,0.934333,0.000000,0.444067,0.124000,0.006983,0.013117,0.031500,0.001017,0.004067,0.001650,...,0.75,282.0,0.0,24.40,0.0,1,1,Friday,14,1
2016-01-01 14:02:00,0.931817,0.000017,0.446067,0.123533,0.006983,0.013083,0.031517,0.001000,0.004067,0.001650,...,0.75,282.0,0.0,24.40,0.0,1,1,Friday,14,2
2016-01-01 14:03:00,1.022050,0.000017,0.446583,0.123133,0.006983,0.013000,0.031500,0.001017,0.004067,0.001617,...,0.75,282.0,0.0,24.40,0.0,1,1,Friday,14,3
2016-01-01 14:04:00,1.139400,0.000133,0.446533,0.122850,0.006850,0.012783,0.031500,0.001017,0.004067,0.001583,...,0.75,282.0,0.0,24.40,0.0,1,1,Friday,14,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-11-30 23:55:00,0.947467,0.000017,0.554633,0.121600,0.007750,0.013167,0.029967,0.000983,0.003150,0.009367,...,0.09,291.0,0.0,11.87,0.0,11,30,Wednesday,23,55
2016-11-30 23:56:00,0.949917,0.000017,0.554433,0.121267,0.007750,0.013183,0.030017,0.001000,0.003167,0.009550,...,0.09,291.0,0.0,11.87,0.0,11,30,Wednesday,23,56
2016-11-30 23:57:00,0.925950,0.000017,0.534500,0.121683,0.007983,0.013167,0.029900,0.000950,0.003150,0.009467,...,0.09,291.0,0.0,11.87,0.0,11,30,Wednesday,23,57
2016-11-30 23:58:00,0.918600,0.000017,0.526267,0.121117,0.007700,0.013183,0.029900,0.000967,0.003150,0.009417,...,0.09,291.0,0.0,11.87,0.0,11,30,Wednesday,23,58
2016-11-30 23:59:00,0.827517,0.000017,0.552450,0.028483,0.007767,0.013217,0.029983,0.000983,0.003167,0.009500,...,0.09,291.0,0.0,11.87,0.0,11,30,Wednesday,23,59

In [11]:
#인덱스 개수
len(df0)

481560

In [15]:
#1분단위의 데이터
df = pd.read_csv("HomeC_11f.csv")
df

,real,predict,month,day,weekday,hour,minute,fare,r_fare,p_fare
0,0.013283,0.005085,11,1,Tuesday,0,1,153.0,0.033872,0.012966
1,0.068133,0.061311,11,1,Tuesday,0,2,153.0,0.173740,0.156344
2,0.118167,0.116248,11,1,Tuesday,0,3,153.0,0.301325,0.296433
3,0.699050,0.721019,11,1,Tuesday,0,4,153.0,1.782577,1.838599
4,0.666250,0.688368,11,1,Tuesday,0,5,153.0,1.698937,1.755340
...,...,...,...,...,...,...,...,...,...,...
43194,0.947467,0.963628,11,30,Wednesday,23,55,153.0,2.416040,2.457251
43195,0.949917,0.965953,11,30,Wednesday,23,56,153.0,2.422288,2.463181
43196,0.925950,0.943164,11,30,Wednesday,23,57,153.0,2.361173,2.405069
43197,0.918600,0.936158,11,30,Wednesday,23,58,153.0,2.342430,2.387203
43198,0.827517,0.848641,11,30,Wednesday,23,59,153.0,2.110168,2.164036

In [25]:
#1일 단위의 사용량과 요금
df1 = df.groupby("day")['real','predict','r_fare','p_fare'].sum()
df1

/tmp/ipykernel_61/2394183446.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df1 = df.groupby("day")['real','predict','r_fare','p_fare'].sum()

            real      predict       r_fare       p_fare
day
1    1334.177483  1294.802092  3455.325426  3323.843429
2     867.111050   869.041188  2144.954258  2138.212005
3     847.550550   868.139286  2096.204628  2140.342591
4     977.212400  1014.628654  2381.409284  2466.540355
5     803.151917   834.383441  1889.957879  1963.594014
6    1411.315483  1390.971311  3534.236297  3468.181856
7    1926.934000  1870.838079  5000.197479  4826.992586
8     902.107917   974.529393  2093.524465  2264.918204
9     965.260583  1018.890465  2338.910800  2475.829406
10   1088.316100  1092.900885  2699.596660  2706.419603
11    906.101983   924.425224  2273.760657  2306.315948
12   1339.934500  1353.990541  3329.635157  3343.325307
13   1279.619083  1299.817892  3239.744433  3280.573612
14    987.885900  1012.932839  2366.032322  2428.801937
15   1229.815333  1225.227079  3153.085787  3123.322577
16   1167.462183  1183.446919  2916.071984  2948.188452
17   1118.741550  1135.714920  2872.493786  2902.968998
18    873.714317   896.235655  2123.178128  2171.126964
19    954.530733   978.468059  2392.926071  2445.481232
20    964.361133   975.018954  2435.088795  2454.547429
21   1558.234233  1543.996649  3891.653791  3834.445929
22   1712.437783  1702.459677  4138.157769  4105.831047
23   1243.704633  1236.850507  3088.893009  3059.232537
24   1345.626133  1347.498233  3221.842591  3226.863803
25   2106.195500  2026.231519  5366.859302  5137.231645
26   1478.615700  1461.825658  3816.752188  3750.030219
27   1084.142833  1097.590554  2616.059305  2644.703893
28   1496.374033  1475.974461  3713.648324  3651.042444
29   1116.201617  1132.283142  2798.801908  2830.761522
30   1423.555117  1419.529537  3563.365358  3545.906466

In [30]:
#사용량 예측 모델과 요금 모델 정확도 계산

#사용량 예측 모델
df1['mape1'] =np.abs((df1['real'] - df1['predict'])/df1['real']*100)
#요금 예측모델
df1['mape2'] =np.abs((df1['r_fare'] - df1['p_fare'])/df1['r_fare']*100)
df1

            real      predict       r_fare       p_fare     mape1     mape2
day
1    1334.177483  1294.802092  3455.325426  3323.843429  2.951286  3.805199
2     867.111050   869.041188  2144.954258  2138.212005  0.222594  0.314331
3     847.550550   868.139286  2096.204628  2140.342591  2.429204  2.105613
4     977.212400  1014.628654  2381.409284  2466.540355  3.828876  3.574819
5     803.151917   834.383441  1889.957879  1963.594014  3.888620  3.896179
6    1411.315483  1390.971311  3534.236297  3468.181856  1.441504  1.868988
7    1926.934000  1870.838079  5000.197479  4826.992586  2.911149  3.463961
8     902.107917   974.529393  2093.524465  2264.918204  8.028028  8.186851
9     965.260583  1018.890465  2338.910800  2475.829406  5.556000  5.853947
10   1088.316100  1092.900885  2699.596660  2706.419603  0.421273  0.252739
11    906.101983   924.425224  2273.760657  2306.315948  2.022205  1.431782
12   1339.934500  1353.990541  3329.635157  3343.325307  1.049010  0.411161
13   1279.619083  1299.817892  3239.744433  3280.573612  1.578502  1.260259
14    987.885900  1012.932839  2366.032322  2428.801937  2.535408  2.652948
15   1229.815333  1225.227079  3153.085787  3123.322577  0.373085  0.943939
16   1167.462183  1183.446919  2916.071984  2948.188452  1.369187  1.101361
17   1118.741550  1135.714920  2872.493786  2902.968998  1.517184  1.060932
18    873.714317   896.235655  2123.178128  2171.126964  2.577655  2.258352
19    954.530733   978.468059  2392.926071  2445.481232  2.507758  2.196272
20    964.361133   975.018954  2435.088795  2454.547429  1.105169  0.799093
21   1558.234233  1543.996649  3891.653791  3834.445929  0.913700  1.470014
22   1712.437783  1702.459677  4138.157769  4105.831047  0.582684  0.781186
23   1243.704633  1236.850507  3088.893009  3059.232537  0.551106  0.960230
24   1345.626133  1347.498233  3221.842591  3226.863803  0.139125  0.155849
25   2106.195500  2026.231519  5366.859302  5137.231645  3.796608  4.278623
26   1478.615700  1461.825658  3816.752188  3750.030219  1.135524  1.748135
27   1084.142833  1097.590554  2616.059305  2644.703893  1.240401  1.094952
28   1496.374033  1475.974461  3713.648324  3651.042444  1.363267  1.685832
29   1116.201617  1132.283142  2798.801908  2830.761522  1.440737  1.141903
30   1423.555117  1419.529537  3563.365358  3545.906466  0.282784  0.489955

In [33]:
#사용량 예측 모델정확도
np.mean(df1['mape1'])

1.9919877595839626

In [34]:
#요금 모델 정확도
np.mean(df1['mape2'])

2.0415135249205907